# Generated by Django 4.1.6 on 2023-02-15 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('-id',), 'verbose_name': 'предмет', 'verbose_name_plural': 'предметы'},
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(verbose_name='цена'),
        ),
    ]
