# Generated by Django 4.1.6 on 2023-02-17 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_item_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='item',
        ),
        migrations.AddField(
            model_name='order',
            name='item',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='orders.item', verbose_name='товар'),
            preserve_default=False,
        ),
    ]
