# Generated by Django 4.1.6 on 2023-02-17 12:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_order_item_order_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=200, verbose_name='название')),
                ('inclusive', models.BooleanField(default=False, verbose_name='включает в стоимость')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='процент')),
                ('country', models.CharField(choices=[('usd', 'USD'), ('eur', 'EUR')], max_length=4, verbose_name='код страны')),
                ('description', models.TextField(verbose_name='описание')),
                ('item', models.ManyToManyField(related_name='tax', to='orders.item', verbose_name='товар')),
            ],
            options={
                'verbose_name': 'налог',
                'verbose_name_plural': 'налоги',
                'ordering': ('-percentage',),
            },
        ),
    ]
