# Generated by Django 4.1.6 on 2023-02-17 12:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tax',
            name='country',
            field=models.CharField(choices=[('US', 'USD'), ('EG', 'EUR')], max_length=4, verbose_name='код страны'),
        ),
        migrations.AlterField(
            model_name='tax',
            name='percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='процент'),
        ),
    ]
