version: '3'

services:
  server:
    build: ./
    container_name: stripe_rishat
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=django_123
      - DEBUG=True
      - STRIPE_PRIVATE_KEY=
      - STRIPE_PUBLIC_KEY=
